/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robotfeliz;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrador
 */
public class RobotDemo extends javax.swing.JFrame {

    Robot mrRoboto;

    /**
     * Creates new form RobotDemo
     */
    public RobotDemo() {
        try {
            this.mrRoboto = new Robot();
        } catch (AWTException ex) {
            Logger.getLogger(RobotDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRobot = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClear.setText("Borrar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtRobot.setColumns(20);
        txtRobot.setRows(5);
        jScrollPane1.setViewportView(txtRobot);

        jMenu1.setText("File");

        jMenuItem1.setText("Iniciar Demo!");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int xTexto;
        int yTexto;
        xTexto = txtRobot.getLocationOnScreen().x + 20;
        System.out.println(xTexto);
        yTexto = txtRobot.getLocationOnScreen().y + 20;
        System.out.println(yTexto);
        mrRoboto.mouseMove(xTexto, yTexto);
        mrRoboto.mousePress(InputEvent.BUTTON1_MASK);
        escribirTexto("Domo arigato Mr. Roboto. Matta ah-oo hima de domo arigato, mr. roboto, himitsu wo shiri tai");
        mrRoboto.keyPress(KeyEvent.VK_ENTER);
        mrRoboto.keyRelease(KeyEvent.VK_ENTER);
        escribirTexto("Este es un bonito demo de como Java puede fingir que es un usuario");
        mrRoboto.keyPress(KeyEvent.VK_ENTER);
        mrRoboto.keyRelease(KeyEvent.VK_ENTER);
        escribirTexto("Como habrás visto, puede mover el mouse, dar click, escribir e incluso tomar capturas de pantalla tal y como lo harías tú. Probemos...");
        mrRoboto.keyPress(KeyEvent.VK_ENTER);
        mrRoboto.keyRelease(KeyEvent.VK_ENTER);
        //  Dimension tamanioPantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //BufferedImage image = mrRoboto.createScreenCapture(new Rectangle(tamanioPantalla));
        //Toolkit.getDefaultToolkit().getSystemClipboard().setContents(new TR, this);
        mrRoboto.keyPress(KeyEvent.VK_PRINTSCREEN);
        mrRoboto.keyRelease(KeyEvent.VK_PRINTSCREEN);
        String sistemaOperativo = System.getProperty("os.name");
        if (sistemaOperativo.toLowerCase().contains("windows")) {
            System.out.println("Windows detectado");
            mrRoboto.keyPress(KeyEvent.VK_WINDOWS);
            mrRoboto.delay(100);
            mrRoboto.keyRelease(KeyEvent.VK_WINDOWS);
            mrRoboto.delay(200);
            escribirTexto("Paint");
            mrRoboto.delay(200);
            mrRoboto.keyPress(KeyEvent.VK_ENTER);
            mrRoboto.keyRelease(KeyEvent.VK_ENTER);
            mrRoboto.delay(200);

        } else if (sistemaOperativo.toLowerCase().contains("linux")) {
            System.out.println("Linux detectado");
            try {
                Runtime.getRuntime().exec("gimp");
            } catch (IOException ex) {
                Logger.getLogger(RobotDemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        mrRoboto.delay(100);
        mrRoboto.keyPress(KeyEvent.VK_CONTROL);
        mrRoboto.delay(100);
        mrRoboto.keyPress(KeyEvent.VK_V);
        mrRoboto.delay(100);
        mrRoboto.keyRelease(KeyEvent.VK_CONTROL);
        mrRoboto.delay(100);
        mrRoboto.keyRelease(KeyEvent.VK_V);
        mrRoboto.delay(200);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtRobot.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RobotDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RobotDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RobotDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RobotDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RobotDemo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtRobot;
    // End of variables declaration//GEN-END:variables

    private void escribirTexto(String textoAEscribir) {
        for (int i = 0; i < textoAEscribir.length(); i++) {
            char letra = textoAEscribir.charAt(i);
            int keycode = KeyEvent.getExtendedKeyCodeForChar(letra);
            try {
                mrRoboto.keyPress(keycode);
                mrRoboto.keyRelease(keycode);
            } catch (IllegalArgumentException e) {
                switch (letra) {
                    case 'á':
                        mrRoboto.keyPress(KeyEvent.VK_ALT);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD6);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD0);
                        mrRoboto.keyRelease(KeyEvent.VK_ALT);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD6);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD0);

                        break;
                    case 'é':
                        mrRoboto.keyPress(KeyEvent.VK_ALT);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD3);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD0);
                        mrRoboto.keyRelease(KeyEvent.VK_ALT);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD3);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD0);
                        break;
                    case 'í':
                        mrRoboto.keyPress(KeyEvent.VK_ALT);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD6);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyRelease(KeyEvent.VK_ALT);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD6);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD1);
                        break;
                    case 'ó':
                        mrRoboto.keyPress(KeyEvent.VK_ALT);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD6);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD2);
                        mrRoboto.keyRelease(KeyEvent.VK_ALT);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD6);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD2);
                        break;
                    case 'ú':
                        mrRoboto.keyPress(KeyEvent.VK_ALT);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD6);
                        mrRoboto.keyPress(KeyEvent.VK_NUMPAD3);
                        mrRoboto.keyRelease(KeyEvent.VK_ALT);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD1);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD6);
                        mrRoboto.keyRelease(KeyEvent.VK_NUMPAD3);
                        break;
                    default:
                        System.err.println("Caracter no identificado!");
                        break;
                }
            }
        }
    }
}
